project:
  type: website

website:
  page-navigation: true
  title: "mp223 Applied Econometric Methods for the Socials Sciences"
  description: "mp223 AEM at JLU Giessen. Summer Semester 2022."
  site-url: "https://ebukin.github.io/mp223-2022-aem-R-public/"
  
  repo-url: https://github.com/EBukin/mp223-2022-aem-R-public/
  repo-actions: [edit, issue]
  
  page-footer:
    right: "This page is built with [Quarto](https://quarto.org/)."
    left: "&copy; Copyright 2022, Eduard Bukin"
    background: "#0168b3"
    
  
  sidebar:
    background: "#989898"
    logo: "img/jlu-logo-1.jfif"
    pinned: true
    align: center
    tools:
      - icon: github
        href: https://github.com/EBukin/mp223-2022-aem-R-public/
        text: "Source code"
      - icon: info-square
        text: "Useful links"
        menu:
          - text: Ilias
            url: https://ilias.uni-giessen.de/goto.php?target=crs_301421&client_id=JLUG
          - text: StudIP
            url: https://studip.uni-giessen.de/dispatch.php/course/details?sem_id=b1775c5097d2a85c2986b7667d22c3dc&again=yes
          - text: Youtube playlist
            url: https://www.youtube.com/playlist?list=PLdj1QiW6P2TcEm0cn1eB6CBQQWLMthjYY
        
    style: "docked"
    search: true
    
    collapse-level: 2
    contents:
      - href: index.qmd
        text: "Course information"
        
      - section: "Weekly checklists"
        contents:
          - href: weeks/week01-checklist.qmd
            text: "Week 1"
          - href: weeks/week03-checklist.qmd
            text: "Week 3"
          - href: weeks/week04-checklist.qmd
            text: "Week 4"
          - href: weeks/week05-checklist.qmd
            text: "Week 5"
          - href: weeks/week06-checklist.qmd
            text: "Week 6"
          - href: weeks/week08-checklist.qmd
            text: "Week 8"
          - href: weeks/week12-checklist.qmd
            text: "Week 12"

  opengraph: true

format:
  html:
    theme:
      light: [cosmo]
      dark: [cosmo]
    mainfont: "Roboto"
    code-copy: true
    code-overflow: wrap
    toc: true

freeze: auto

editor: visual

